#!/usr/bin/env python3
"""Generate the evergreen guide-system pages for atapamukcu.com."""
from pathlib import Path
import json

ROOT = Path(__file__).resolve().parents[1]
BASE = "https://www.atapamukcu.com"
DATE = "2026-07-27"
IMG = f"{BASE}/images/hero-photo.jpg"

NAV = '''<header class="site-header" id="header"><div class="container"><div class="nav-inner">
<a href="/" class="logo">ATA PAMUKÇU</a><nav class="nav-right"><a href="/">ANA SAYFA</a><a href="/baslangic">BAŞLANGIÇ</a><a href="/hakkimda">HAKKIMDA</a><a href="/site-haritasi">REHBER</a><a href="/araclar">ARAÇLAR</a><a href="/psikoloji-3">PSİKOLOJİ 3.0</a><a href="/#iletisim">İLETİŞİM</a></nav>
</div></div></header>'''

FOOTER = '''<footer class="site-footer" id="iletisim"><div class="container"><div class="footer-grid"><div class="footer-col"><h3>ATA PAMUKÇU</h3><p><a href="/hakkimda">Hakkımda</a></p><p><a href="/site-haritasi">Rehber kütüphanesi</a></p><p><a href="/araclar">Araçlar</a></p></div><div class="footer-col"><h3>YER</h3><p>ANTALYA</p></div><div class="footer-col"><h3>İLETİŞİM</h3><p><a href="mailto:atapamukcu@gmail.com">ATAPAMUKCU@GMAIL.COM</a></p><p><a href="tel:+905327624060">(532) 762-4060</a></p></div></div></div></footer>'''

ANALYTICS = '''<script src="/js/script.js" defer></script><script>window.dataLayer=window.dataLayer||[];function gtag(){dataLayer.push(arguments)}window.addEventListener('load',function(){var f=function(){var s=document.createElement('script');s.async=true;s.src='https://www.googletagmanager.com/gtag/js?id=G-M1K0Q69Q2Z';document.head.appendChild(s);gtag('js',new Date());gtag('config','G-M1K0Q69Q2Z')};if('requestIdleCallback'in window)requestIdleCallback(f,{timeout:15000});else setTimeout(f,15000)});</script>'''

def schema_script(data):
    return '<script type="application/ld+json">' + json.dumps(data, ensure_ascii=False, indent=2) + '</script>'

def source_schema(urls):
    return urls

def page(path, title, description, eyebrow, h1, lead, body, schema_type="Article", sources=None, extra_schema=None, extra_scripts="", og_type="article", analytics=True):
    canonical = BASE + path
    schemas = [{
        "@context": "https://schema.org", "@type": schema_type, "@id": canonical + "#main",
        "headline" if schema_type in ("Article", "HowTo") else "name": h1,
        "name": h1, "description": description, "url": canonical, "inLanguage": "tr-TR",
        "datePublished": DATE, "dateModified": DATE,
        "author": {"@type":"Person", "name":"Ata Pamukçu", "url":BASE + "/hakkimda"},
        "publisher": {"@type":"Organization", "name":"Psikolog Ata Pamukçu", "url":BASE},
        "image": IMG,
        **({"citation": source_schema(sources)} if sources else {})
    }, {
        "@context":"https://schema.org", "@type":"BreadcrumbList", "itemListElement":[
            {"@type":"ListItem","position":1,"name":"Ana Sayfa","item":BASE+"/"},
            {"@type":"ListItem","position":2,"name":h1,"item":canonical}
        ]
    }]
    if extra_schema: schemas.extend(extra_schema)
    html = f'''<!DOCTYPE html><html lang="tr"><head>
<meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>{title}</title><meta name="description" content="{description}"><link rel="canonical" href="{canonical}"><meta name="robots" content="index, follow">
<meta property="og:title" content="{title}"><meta property="og:description" content="{description}"><meta property="og:url" content="{canonical}"><meta property="og:type" content="{og_type}"><meta property="og:locale" content="tr_TR"><meta property="og:image" content="{IMG}">
<meta name="twitter:card" content="summary_large_image"><meta name="twitter:title" content="{title}"><meta name="twitter:description" content="{description}"><meta name="twitter:image" content="{IMG}">
<link rel="stylesheet" href="/css/style.css?v=20260727-evergreen">{('<link rel="preconnect" href="https://www.googletagmanager.com"><link rel="dns-prefetch" href="https://www.googletagmanager.com">' if analytics else '')}
{''.join(schema_script(s) for s in schemas)}
<link rel="alternate" type="text/markdown" href="/llms.txt" title="AI-readable site summary"><link rel="alternate" type="application/json" href="/ai-context.json" title="AI-readable entity context"><link rel="icon" href="/favicon.ico" sizes="any"></head><body>
<a href="#main" class="skip-link">İÇERİĞE ATLAYIN</a>{NAV}<main id="main"><section class="article-hero"><div class="container article-container"><p class="section-eyebrow">{eyebrow}</p><h1>{h1}</h1><p class="article-lead">{lead}</p><p class="article-meta"><a href="/hakkimda" rel="author">Psikolog Ata Pamukçu</a> <span>·</span> <time datetime="{DATE}">27 Temmuz 2026'da güncellendi</time></p></div></section>
<nav class="breadcrumb" aria-label="Sayfa yolu"><a href="/">ANA SAYFA</a><span class="breadcrumb-sep">/</span><span>{h1}</span></nav>
<section class="article-section"><div class="container article-container">{body}</div></section></main>{FOOTER}{extra_scripts}{(ANALYTICS if analytics else '<script src="/js/script.js" defer></script>')}</body></html>'''
    file = ROOT / (path.strip("/") + ".html")
    file.parent.mkdir(parents=True, exist_ok=True)
    file.write_text(html, encoding="utf-8")
    return file

SOURCES_ANXIETY = [
    "https://www.nimh.nih.gov/health/topics/anxiety-disorders",
    "https://www.nice.org.uk/guidance/cg113",
    "https://doi.org/10.1016/j.brat.2014.04.006"
]

kaygi_body = '''
<nav class="content-type-nav" aria-label="İçerik türleri"><a href="/site-haritasi#rehberler">Rehber</a><a href="/uygulamalar/kacinma-haritasi">Uygulama</a><a href="/araclar/islevsel-takip">Araç</a><a href="/ogrenme-yollari/kaygi">Öğrenme yolu</a></nav>
<section class="article-card muted"><h2>Kısa cevap</h2><p><strong>Kaygı döngüsü</strong>, bir tetikleyicinin tehdit olarak yorumlanmasıyla başlayan; bedensel alarm, kaçınma veya kontrol davranışları ve kısa süreli rahatlamayla sürdürülen bir öğrenme döngüsüdür. Sorun kaygının tek başına varlığı değildir. Rahatlamak için yapılan davranışlar yaşam alanını daraltıyor ve “ancak kaçarsam güvendeyim” öğrenmesini güçlendiriyorsa döngü kalıcılaşabilir.</p><p class="reading-time">Yaklaşık okuma süresi: 9 dakika</p></section>
<section class="article-card"><h2>Kaygı neden bir döngüye dönüşür?</h2><p>Kaygı, olası tehlikeye hazırlanmayı sağlayan insani bir alarm sistemidir. Belirsizlik, bedensel bir duyum, bir düşünce veya gerçek bir durum bu alarmı başlatabilir. Zihin daha sonra “ya kötü bir şey olursa?” senaryoları üretir; bedende çarpıntı, gerginlik, terleme veya huzursuzluk fark edilebilir.</p><p>Bu noktada kişi toplantıda konuşmamak, nabzını kontrol etmek, sürekli güvence sormak, internetten belirti aramak ya da planı ertelemek gibi davranışlara yönelebilir. Bu davranışlar çoğu zaman kötü kararlar değildir; o anda rahatlatırlar. Fakat tam da bu rahatlama, davranışın yeniden yapılma olasılığını artırabilir.</p></section>
<section aria-labelledby="dongu-baslik"><h2 id="dongu-baslik">Kaygı döngüsünün altı halkası</h2><div class="guide-flow">
<div class="flow-step"><span class="flow-number">1</span><div><h3>Tetikleyici</h3><p>Bir durum, düşünce, anı, belirsizlik veya beden duyumu alarmı başlatır.</p></div></div>
<div class="flow-step"><span class="flow-number">2</span><div><h3>Tehdit yorumu</h3><p>Zihin olasılığı kesinlik gibi okuyabilir: “Kontrolümü kaybedeceğim”, “rezil olacağım” veya “bu belirti tehlikeli”.</p></div></div>
<div class="flow-step"><span class="flow-number">3</span><div><h3>Bedensel alarm</h3><p>Kalp atışı, nefes, kas gerginliği ve dikkat değişir. Duyumları tehdit olarak okumak alarmı büyütebilir.</p></div></div>
<div class="flow-step"><span class="flow-number">4</span><div><h3>Kaçınma ve güvenlik davranışı</h3><p>Kişi ortamdan çıkar, erteler, kontrol eder, hazırlanmayı uzatır veya güvence arar.</p></div></div>
<div class="flow-step"><span class="flow-number">5</span><div><h3>Kısa vadeli rahatlama</h3><p>Kaygı azalabilir. Beyin, rahatlamayı kaçınmaya bağlayarak bu davranışı öğrenir.</p></div></div>
<div class="flow-step"><span class="flow-number">6</span><div><h3>Uzun vadeli maliyet</h3><p>Kişi yeni bilgi edinemez, öz-yeterlik azalabilir ve okul, iş, ilişki veya hareket alanı daralabilir.</p></div></div>
</div></section>
<section class="article-card muted"><h2>Bir örnek: toplantıda söz almak</h2><p>Tetikleyici, yaklaşan ekip toplantısıdır. “Takılırsam herkes yetersiz olduğumu anlar” düşüncesiyle kalp hızlanır. Kişi notlarını tekrar tekrar düzeltir ve toplantıda konuşmaz. O an rahatlar; fakat fikrini ifade edebileceğini veya küçük bir hatanın tolere edilebildiğini öğrenme fırsatı oluşmaz. Bir sonraki toplantı daha tehdit edici hissedebilir.</p></section>
<section class="article-card"><h2>Kaygıyı azaltmaya çalışmak ne zaman sorun olur?</h2><p>Her rahatlama davranışı işlevsiz değildir. Dinlenmek, plan yapmak veya destek istemek bağlama göre yararlı olabilir. Ayırt edici soru davranışın biçimi değil <strong>işlevidir</strong>: Bu davranış yalnızca o anki iç deneyimi susturmak için mi yapılıyor, zaman içinde esnekliği ve önemli yaşam alanlarını azaltıyor mu?</p><table class="comparison-table"><thead><tr><th>Bakılacak soru</th><th>Kısa vade</th><th>Uzun vade</th></tr></thead><tbody><tr><td>Ne sağladı?</td><td>Rahatlama, belirsizliğin azalması</td><td>Yeni öğrenme veya yaşam alanı oluştu mu?</td></tr><tr><td>Ne öğretti?</td><td>“Bunu yapınca kaygı azalıyor”</td><td>“Kaygı varken de hareket edebilirim” bilgisi oluştu mu?</td></tr><tr><td>Bedeli ne?</td><td>Çoğu zaman görünmez</td><td>Zaman, ilişki, iş, okul veya özgürlük kaybı</td></tr></tbody></table></section>
<section class="article-card"><h2>Döngü nasıl değişir?</h2><p>Hedef kaygıyı zorla sıfırlamak değildir. Önce döngü somut bir olay üzerinden haritalanır. Ardından güvenlik davranışlarından biri seçilir ve kişinin değer verdiği yöne hizmet eden, yeterince küçük bir alternatif denenir. Exposure ya da üstüne gitme çalışmaları “dayan ve kaygıyı düşür” sınavı değil; tahminleri test etme, farklı sonuçları fark etme ve davranış repertuvarını genişletme fırsatı olarak ele alınır.</p><div class="guide-callout"><strong>İlk uygulanabilir adım:</strong><p>Son bir olayı seçin. “Ne oldu → zihnim ne dedi → bedenimde ne oldu → ne yaptım → o an ne sağladı → uzun vadede neye mal oldu?” sırasıyla yazın. Ardından yalnızca tek davranışta yüzde 10'luk bir esneme belirleyin.</p></div></section>
<section class="article-card muted"><h2>Profesyonel ve acil destek</h2><p>Kaygı haftalar boyunca sürüyor, günlük işlevselliği belirgin biçimde etkiliyor, kaçınma alanı genişliyor ya da kendi başınıza denediğiniz adımlar döngüyü daha da katılaştırıyorsa bir ruh sağlığı uzmanından değerlendirme almak yararlı olabilir.</p><p><strong>Bu rehber tanı değildir.</strong> Göğüs ağrısı, ciddi nefes darlığı, bayılma veya ilk kez yaşanan şiddetli belirtileri otomatik olarak panik saymayın; psikolojik açıklama varsaymadan acil/tıbbi değerlendirme alın.</p></section>
<section class="author-note article-card"><p class="author-note-kicker">Editoryal sorumluluk</p><h2>Psikolog Ata Pamukçu tarafından hazırlanmıştır</h2><p>Bu rehber genel psikolojik bilgilendirme içindir; tanı veya kişisel tedavi planı değildir. Klinik çalışmamda davranışın bağlamını, kısa vadeli işlevini ve uzun vadeli sonuçlarını birlikte değerlendiririm.</p><p><a href="/hakkimda">Eğitim ve çalışma yaklaşımı</a></p></section>
<div class="related-pages"><h2>Buradan devam edin</h2><div class="related-grid"><a href="/uygulamalar/kacinma-haritasi" class="related-card"><span><strong>Kaçınma Haritası</strong><br>Kısa ve uzun vadeli sonuçları ayırın.</span></a><a href="/araclar/kaygi-dongusu-haritasi" class="related-card"><span><strong>Kaygı Döngüsü Aracı</strong><br>Tek bir olayı ayrıntılı haritalayın.</span></a><a href="/araclar/islevsel-takip" class="related-card"><span><strong>İşlevsel Takip</strong><br>Örüntüyü birden fazla olayda izleyin.</span></a><a href="/ogrenme-yollari/kaygi" class="related-card"><span><strong>Kaygı Öğrenme Yolu</strong><br>Sayfaları önerilen sırada ilerletin.</span></a></div></div>
<section class="article-sources" aria-labelledby="kaynakca"><h2 id="kaynakca">Kaynakça ve ileri okuma</h2><ul><li><strong>NIMH:</strong> <a href="https://www.nimh.nih.gov/health/topics/anxiety-disorders" target="_blank" rel="noopener noreferrer">Anxiety Disorders</a></li><li><strong>NICE:</strong> <a href="https://www.nice.org.uk/guidance/cg113" target="_blank" rel="noopener noreferrer">Generalised anxiety disorder and panic disorder in adults (CG113)</a></li><li><strong>Craske ve ark. (2014):</strong> <a href="https://doi.org/10.1016/j.brat.2014.04.006" target="_blank" rel="noopener noreferrer">Maximizing exposure therapy: An inhibitory learning approach</a></li></ul><p class="source-note">Kaynaklar genel çerçeveyi destekler; kişisel değerlendirme yerine geçmez.</p></section>'''

page("/kaygi-dongusu", "Kaygı Döngüsü: Kaçınma ve Rahatlama Döngüsü Nasıl Sürer?", "Kaygı döngüsünün tetikleyici, tehdit yorumu, bedensel alarm, kaçınma ve kısa vadeli rahatlamayla nasıl sürdüğünü örneklerle anlayın.", "Kapsamlı rehber", "Kaygı Döngüsü", "Kaygı neden tekrar tekrar aynı yere dönüyor? Döngünün parçalarını, kısa vadeli rahatlamanın rolünü ve değişimin nereden başlayabileceğini işlevsel bir çerçeveyle inceleyin.", kaygi_body, sources=SOURCES_ANXIETY)

avoid_sources = ["https://www.nice.org.uk/guidance/cg113", "https://doi.org/10.1037/0022-006X.64.6.1152", "https://doi.org/10.1016/j.brat.2014.04.006"]
avoid_body = '''
<nav class="content-type-nav" aria-label="İçerik türleri"><a href="/kaygi-dongusu">Önce rehberi okuyun</a><a href="/araclar/islevsel-takip">Takip aracına geçin</a><a href="/ogrenme-yollari/kaygi">Öğrenme yolu</a></nav>
<section class="article-card muted"><h2>Bu uygulamanın amacı</h2><p>Kaçınma Haritası, bir davranışın yalnızca “kaçınma” adını alıp almadığına değil, <strong>o anda ne işe yaradığına ve zaman içinde neye mal olduğuna</strong> bakar. Yaklaşık 10–15 dakika sürer.</p><h3>Ne değildir?</h3><p>Tanı koymaz, exposure planı oluşturmaz ve profesyonel değerlendirme yerine geçmez.</p></section>
<section class="article-card"><h2>Hazırlık</h2><ul class="article-list"><li>Yakın zamanda yaşanmış, yoğunluğu düşük veya orta düzeyde tek bir olayı seçin.</li><li>Genel kişilik yorumu yerine gözlenebilir bir davranış yazın: “kaçtım” yerine “mesajı açmadım”.</li><li>Çalışmayı sakin ve güvenli bir yerde yapın. Araç tarayıcıda çalışır; girdiler sunucuya gönderilmez veya kalıcı kaydedilmez.</li></ul></section>
<form class="article-card practice-form" id="avoidanceForm"><h2>Kaçınma haritanızı oluşturun</h2>
<label for="aSituation">1. Durum neydi?</label><textarea id="aSituation" rows="3" required placeholder="Örn. Toplantıda görüşüm soruldu."></textarea>
<label for="aInside">2. Hangi düşünce, duygu veya beden duyumundan uzaklaşmak istediniz?</label><textarea id="aInside" rows="3" required placeholder="Örn. Yetersiz görünme düşüncesi ve göğüste sıkışma."></textarea>
<label for="aAction">3. Tam olarak ne yaptınız veya yapmadınız?</label><textarea id="aAction" rows="3" required placeholder="Örn. Kısa cevap verdim ve fikrimi söylemedim."></textarea>
<label for="aShort">4. Bu davranış kısa vadede ne sağladı?</label><textarea id="aShort" rows="3" required placeholder="Örn. Görünür olma kaygım azaldı."></textarea>
<label for="aLong">5. Uzun vadede neye mal olabilir?</label><textarea id="aLong" rows="3" required placeholder="Örn. Katkımı sunamamak ve toplantılardan daha fazla çekinmek."></textarea>
<label for="aValue">6. Bu durumda hangi yön veya değer önemliydi?</label><textarea id="aValue" rows="3" placeholder="Örn. Katkı sunmak, açıklık, mesleki gelişim."></textarea>
<label for="aTiny">7. Bir sonraki sefer yüzde 10 daha esnek davranış ne olabilir?</label><textarea id="aTiny" rows="3" placeholder="Örn. En az bir cümleyle görüşümü söylemek."></textarea>
<div class="action-row"><button type="submit" class="btn-primary">Haritayı oluştur</button><button type="button" class="btn-secondary" id="avoidCopy">Metni kopyala</button><button type="button" class="btn-secondary" id="avoidPrint">Yazdır / PDF</button><button type="button" class="btn-secondary" id="avoidClear">Formu temizle</button></div><p class="tool-status" id="avoidStatus" role="status" aria-live="polite"></p></form>
<section class="article-card" id="avoidResult" hidden><h2>Kaçınma haritanız</h2><pre class="tool-result" id="avoidOutput"></pre></section>
<section class="article-card muted"><h2>Kısa örnek</h2><p><strong>Durum:</strong> Bir arkadaşın mesajı geldi. <strong>İç deneyim:</strong> “Yanlış bir şey söylerim” düşüncesi ve gerginlik. <strong>Davranış:</strong> Mesajı iki gün açmamak. <strong>Kısa vade:</strong> Gerginliğin azalması. <strong>Uzun vade:</strong> Yakınlığın ve kendiliğindenliğin azalması. <strong>Küçük esneme:</strong> Kusursuz cevap hazırlamadan aynı gün kısa bir dönüş yapmak.</p></section>
<section class="article-card"><h2>Sık yapılan hatalar</h2><ul class="article-list"><li>Haritayı kendini eleştirme listesine çevirmek.</li><li>Tek olay yerine bütün hayatı çözmeye çalışmak.</li><li>Alternatif adımı “bir daha hiç kaçınmayacağım” kadar büyük yazmak.</li><li>Başarı ölçütünü yalnızca kaygının düşmesi yapmak. Ölçüt, seçilen davranışın denenip denenmediğidir.</li></ul></section>
<div class="safety-grid"><section class="library-card"><span class="library-label">Durma ölçütü</span><h2>Ne zaman ara verilmeli?</h2><p>Çalışma sırasında yönelim kaybı, yoğun dissosiyasyon, dayanılması güç panik, kendine zarar verme düşüncesi veya belirgin güvenlik riski oluşursa uygulamayı bırakın ve uygun profesyonel/acil desteğe başvurun.</p></section><section class="library-card"><span class="library-label">Uygun olmayabilir</span><h2>Kimin için uygun olmayabilir?</h2><p>Travmatik anıları ayrıntılı canlandırmak, tıbbi olarak değerlendirilmemiş yeni belirtileri psikolojik saymak veya yüksek riskli davranışlara tek başına üstüne gitmek için uygun değildir. Gerçek tehlikeden uzaklaşmak “kaçınma” değil, güvenlik davranışıdır.</p></section></div>
<section class="guide-callout warning"><strong>Acil destek:</strong><p>Kendinize veya başkasına zarar verme riski, güvenliğinizi sürdürememe ya da acil tıbbi durum varsa bu sayfayı kullanmak yerine 112'yi arayın veya en yakın acil servise başvurun.</p></section>
<section class="author-note article-card"><p class="author-note-kicker">Editoryal sorumluluk</p><h2>Psikolog Ata Pamukçu tarafından hazırlanmıştır</h2><p>Bu uygulama psikoeğitim amaçlıdır. Kişisel değerlendirme veya tedavi yönergesi sunmaz.</p></section>
<section class="article-sources" aria-labelledby="uygulama-kaynakca"><h2 id="uygulama-kaynakca">Kaynakça</h2><ul><li><strong>NICE:</strong> <a href="https://www.nice.org.uk/guidance/cg113" target="_blank" rel="noopener noreferrer">GAD and panic disorder in adults (CG113)</a></li><li><strong>Hayes ve ark. (1996):</strong> <a href="https://doi.org/10.1037/0022-006X.64.6.1152" target="_blank" rel="noopener noreferrer">Experiential avoidance and behavioral disorders</a></li><li><strong>Craske ve ark. (2014):</strong> <a href="https://doi.org/10.1016/j.brat.2014.04.006" target="_blank" rel="noopener noreferrer">Maximizing exposure therapy</a></li></ul><p class="source-note">Kaynaklar uygulamanın kavramsal çerçevesini destekler; bu sayfa bir tedavi protokolü değildir.</p></section>'''

page("/uygulamalar/kacinma-haritasi", "Kaçınma Haritası: Kısa ve Uzun Vadeli İşlev Uygulaması", "Kaçınma davranışının o anda ne sağladığını, uzun vadede neye mal olduğunu ve küçük bir esneme adımını güvenli biçimde haritalayın.", "Güvenli psikoeğitim uygulaması", "Kaçınma Haritası", "Bir davranışı iyi veya kötü diye etiketlemek yerine kısa vadeli işleviyle uzun vadeli maliyetini yan yana görün.", avoid_body, schema_type="SoftwareApplication", sources=avoid_sources, extra_scripts='<script src="/js/avoidance-map.js?v=20260727" defer></script>', analytics=False)

tracker_sources = ["https://doi.org/10.1016/j.cpr.2020.101908", "https://www.nimh.nih.gov/health/topics/anxiety-disorders", "https://doi.org/10.1016/j.brat.2014.04.006"]
tracker_body = '''
<nav class="content-type-nav" aria-label="İçerik türleri"><a href="/kaygi-dongusu">Mekanizmayı okuyun</a><a href="/uygulamalar/kacinma-haritasi">Tek olay uygulaması</a><a href="/ogrenme-yollari/kaygi">Öğrenme yolu</a></nav>
<section class="article-card muted"><h2>Amaç ve veri güvenliği</h2><p>İşlevsel Takip, benzer olaylarda tekrarlayan tetikleyici–davranış–sonuç örüntüsünü görünür kılmak için hazırlanmıştır. Kayıtlar yalnızca bu sekme açıkken bellekte tutulur; sunucuya gönderilmez ve tarayıcı depolamasına yazılmaz. Sayfayı yenilerseniz kayıtlar silinir. İsterseniz CSV indirerek veya yazdırarak kendiniz saklayabilirsiniz.</p><p><strong>Bu araç tanı testi, otomatik klinik yorum veya kişisel tedavi planı değildir.</strong></p></section>
<form class="article-card practice-form" id="trackerForm"><h2>Yeni olay ekleyin</h2><div class="form-grid"><div><label for="tDate">Tarih</label><input type="date" id="tDate" required></div><div><label for="tContext">Bağlam</label><input type="text" id="tContext" required placeholder="Toplantı, ev, ulaşım..."></div></div>
<label for="tTrigger">Öncesinde ne oldu?</label><textarea id="tTrigger" rows="2" required placeholder="Somut tetikleyici veya durum"></textarea>
<label for="tInside">Düşünce, duygu ve beden</label><textarea id="tInside" rows="2" placeholder="Kısa ve gözlenebilir yazın"></textarea>
<label for="tAction">Ne yaptınız veya yapmadınız?</label><textarea id="tAction" rows="2" required placeholder="Davranış"></textarea>
<div class="form-grid"><div><label for="tShort">Kısa vadede ne sağladı?</label><textarea id="tShort" rows="2" required></textarea></div><div><label for="tLong">Uzun vadede ne oldu?</label><textarea id="tLong" rows="2"></textarea></div></div>
<label for="tNext">Bir sonraki küçük ve uygulanabilir adım</label><textarea id="tNext" rows="2"></textarea>
<div class="action-row"><button type="submit" class="btn-primary">Kaydı ekle</button><button type="button" class="btn-secondary" id="downloadCsv">CSV indir</button><button type="button" class="btn-secondary" id="printTracker">Yazdır / PDF</button><button type="button" class="btn-secondary" id="clearTracker">Tüm kayıtları temizle</button></div><p class="tool-status" id="trackerStatus" role="status" aria-live="polite"></p></form>
<section class="article-card"><h2>Bu oturumdaki kayıtlar</h2><p class="empty-state" id="trackerEmpty">Henüz kayıt eklenmedi.</p><div class="tracker-table-wrap"><table class="tracker-table" id="trackerTable" hidden><thead><tr><th>Tarih / bağlam</th><th>Öncesi ve iç deneyim</th><th>Davranış</th><th>Kısa / uzun sonuç</th><th>Sonraki adım</th></tr></thead><tbody id="trackerRows"></tbody></table></div></section>
<section class="article-card"><h2>Nasıl yorumlanır?</h2><p>Üç veya daha fazla kayıt oluştuğunda aynı davranışın hangi koşullarda tekrarlandığına bakın. Özellikle kısa vadede hızla rahatlatan ama uzun vadede yaşam alanını daraltan örüntüler değişim adayı olabilir. Tek bir kayıttan kesin sonuç çıkarmayın; bağlam değiştiğinde aynı davranışın işlevi de değişebilir.</p><div class="guide-callout"><strong>İyi bir takip sorusu:</strong><p>“Hangi belirti kaç puandı?” sorusuna ek olarak “Bu durumda ne yaptım ve bu davranış beni kısa ve uzun vadede nereye götürdü?” diye sorun.</p></div></section>
<section class="article-card muted"><h2>Ne zaman kullanmamalı?</h2><p>Bu aracı kendinizi sürekli kontrol etmek, güvence üretmek veya her iç deneyimi sayısallaştırmak için kullanmayın. Kayıt tutmak kaygıyı belirgin artırıyor, günlük yaşamı bölüyor veya kompulsif bir nitelik kazanıyorsa ara verin. Kendine zarar verme riski, güvenliği sürdürememe veya acil tıbbi durumda 112'yi arayın ya da en yakın acil servise başvurun.</p></section>
<section class="author-note article-card"><p class="author-note-kicker">Editoryal sorumluluk</p><h2>Psikolog Ata Pamukçu tarafından hazırlanmıştır</h2><p>Araç, davranışların işlevini bağlam içinde gözlemlemeye yardımcı olmak üzere tasarlanmıştır; otomatik yorum üretmez.</p></section>
<section class="article-sources" aria-labelledby="takip-kaynakca"><h2 id="takip-kaynakca">Kaynakça</h2><ul><li><strong>Hayes, Hofmann ve Ciarrochi (2020):</strong> <a href="https://doi.org/10.1016/j.cpr.2020.101908" target="_blank" rel="noopener noreferrer">A process-based approach to psychological diagnosis and treatment: The conceptual and treatment utility of an extended evolutionary meta model</a></li><li><strong>NIMH:</strong> <a href="https://www.nimh.nih.gov/health/topics/anxiety-disorders" target="_blank" rel="noopener noreferrer">Anxiety Disorders</a></li><li><strong>Craske ve ark. (2014):</strong> <a href="https://doi.org/10.1016/j.brat.2014.04.006" target="_blank" rel="noopener noreferrer">Maximizing exposure therapy</a></li></ul></section>'''

page("/araclar/islevsel-takip", "İşlevsel Takip Formu | Tarayıcıda Çalışan Psikolojik Araç", "Tetikleyici, davranış, kısa ve uzun vadeli sonuçları birden fazla olayda izleyin; kayıtları sunucuya göndermeden CSV olarak indirin.", "Tekrar kullanılabilir çalışma aracı", "İşlevsel Takip Formu", "Belirti puanından fazlasını görün: Bir davranışın hangi bağlamda tekrarlandığını, o anda ne sağladığını ve zaman içinde nereye götürdüğünü izleyin.", tracker_body, schema_type="SoftwareApplication", sources=tracker_sources, extra_scripts='<script src="/js/functional-tracker.js?v=20260727" defer></script>', analytics=False)

path_sources = SOURCES_ANXIETY
path_body = '''
<section class="article-card muted"><h2>Bu yol kimler için?</h2><p>Kaygının nasıl sürdüğünü anlamak, kendi döngüsünü düşük riskli bir örnek üzerinden görmek ve profesyonel destek gerekip gerekmediğini değerlendirmek isteyen yetişkinler için hazırlanmıştır. Bu yol tanı veya kendi kendine tedavi programı değildir. Adımları aynı gün bitirmek zorunda değilsiniz.</p><p class="reading-time">Önerilen tempo: 3–7 gün içinde, toplam 45–70 dakika.</p></section>
<div class="guide-flow" aria-label="Kaygı öğrenme adımları">
<div class="flow-step"><span class="flow-number">1</span><div><span class="library-label">Tanı</span><h3>Kaygının genel çerçevesini okuyun</h3><p>Kaygının normal alarm işleviyle günlük yaşamı daraltan örüntüleri ayırın.</p><p><a href="/genel-kaygi">Genel kaygı rehberine geçin →</a></p></div></div>
<div class="flow-step"><span class="flow-number">2</span><div><span class="library-label">Anla</span><h3>Döngünün nasıl sürdüğünü öğrenin</h3><p>Tetikleyici, tehdit yorumu, beden, kaçınma ve kısa vadeli rahatlama arasındaki bağlantıyı kurun.</p><p><a href="/kaygi-dongusu">Kaygı Döngüsü rehberine geçin →</a></p></div></div>
<div class="flow-step"><span class="flow-number">3</span><div><span class="library-label">Uygula</span><h3>Tek bir kaçınma örneğini haritalayın</h3><p>Yoğunluğu düşük veya orta bir olay seçip kısa vadeli işlevle uzun vadeli maliyeti ayırın.</p><p><a href="/uygulamalar/kacinma-haritasi">Kaçınma Haritasını açın →</a></p></div></div>
<div class="flow-step"><span class="flow-number">4</span><div><span class="library-label">Takip et</span><h3>Örüntünün tekrarını gözlemleyin</h3><p>Bir hafta içinde birkaç olayı kaydedin; tek olaydan kesin sonuç çıkarmayın.</p><p><a href="/araclar/islevsel-takip">İşlevsel Takip Formunu açın →</a></p></div></div>
<div class="flow-step"><span class="flow-number">5</span><div><span class="library-label">Derinleş</span><h3>Esneklik ve üstüne gitme mantığını okuyun</h3><p>Hedefi yalnızca rahatlamak değil, değer verilen yönde daha geniş davranabilmek olarak kurun.</p><p><a href="/psikolojik-esneklik">Psikolojik esneklik</a> · <a href="/maruz-birakma-terapisi">Maruz bırakma / exposure</a></p></div></div>
<div class="flow-step"><span class="flow-number">6</span><div><span class="library-label">Destek</span><h3>Gerekirse değerlendirme alın</h3><p>Kaçınma genişliyorsa, işlevsellik belirgin etkileniyorsa veya adımlar güvenli biçimde uygulanamıyorsa profesyonel destek düşünün.</p><p><a href="/surec">Görüşme süreci nasıl ilerler? →</a></p></div></div>
</div>
<section class="guide-callout warning"><strong>Profesyonel ve acil destek:</strong><p>İlk kez yaşanan veya tıbbi olabilecek belirtilerde önce sağlık değerlendirmesi alın. Göğüs ağrısı, ciddi nefes darlığı, bayılma veya ilk şiddetli belirtileri otomatik olarak panik saymayın. Travmatik anılar, yoğun dissosiyasyon, kendine zarar verme düşüncesi veya gerçek güvenlik riskiyle tek başınıza çalışma yapmayın. Acil durumda 112'yi arayın.</p></section>
<section class="article-card"><h2>Yolu tamamlarken üç ölçüt</h2><ol class="article-list"><li><strong>Anlama:</strong> Döngüyü soyut etiketler yerine tek bir olay üzerinden anlatabiliyor musunuz?</li><li><strong>Davranış:</strong> Kaygının düzeyinden bağımsız, denemek istediğiniz küçük davranışı belirleyebiliyor musunuz?</li><li><strong>İşlev:</strong> Bir davranışın kısa vadeli yararıyla uzun vadeli maliyetini birlikte görebiliyor musunuz?</li></ol></section>
<section class="author-note article-card"><p class="author-note-kicker">Editoryal sorumluluk</p><h2>Psikolog Ata Pamukçu tarafından hazırlanmıştır</h2><p>Öğrenme yolu, sitedeki genel bilgilendirme içeriklerini güvenli ve mantıklı bir sıraya koyar; kişisel tedavi planı değildir.</p></section>
<section class="article-sources" aria-labelledby="yol-kaynakca"><h2 id="yol-kaynakca">Kaynakça</h2><ul><li><strong>NIMH:</strong> <a href="https://www.nimh.nih.gov/health/topics/anxiety-disorders" target="_blank" rel="noopener noreferrer">Anxiety Disorders</a></li><li><strong>NICE:</strong> <a href="https://www.nice.org.uk/guidance/cg113" target="_blank" rel="noopener noreferrer">GAD and panic disorder in adults</a></li><li><strong>Craske ve ark.:</strong> <a href="https://doi.org/10.1016/j.brat.2014.04.006" target="_blank" rel="noopener noreferrer">Inhibitory learning approach</a></li></ul></section>'''

page("/ogrenme-yollari/kaygi", "Kaygı Öğrenme Yolu | Tanı, Anla, Uygula, Takip Et", "Kaygıyı genel çerçeveden işlevsel takibe kadar tanı, anla, uygula, takip et ve destek adımlarıyla sıralı biçimde öğrenin.", "Sıralı öğrenme yolu", "Kaygıyı Anlama ve Çalışma Yolu", "Birbiriyle bağlantılı rehber, uygulama ve araçları rastgele değil; güvenli ve öğretici bir sırayla ilerletin.", path_body, schema_type="CollectionPage", sources=path_sources, og_type="website")

library_body = '''
<nav class="content-type-nav" aria-label="Kütüphane bölümleri"><a href="#psikolojik-sorunlar">Psikolojik sorunlar</a><a href="#ogrenme-yollari">Öğrenme yolları</a><a href="#rehberler">Rehberler</a><a href="#uygulamalar">Uygulamalar</a><a href="#araclar">Araçlar</a><a href="#yaklasimlar">Yaklaşımlar</a></nav>
<section class="article-card muted"><h2>Bu kütüphane nasıl kullanılır?</h2><p>Yaşadığınız zorlanmayı genel hatlarıyla anlamak istiyorsanız <strong>psikolojik sorunlar</strong> bölümünden başlayın. Bir konuyu adım adım incelemek için öğrenme yolunu; tek bir mekanizmayı anlamak için rehberi; yazılı bir deneme yapmak için uygulamayı; birden fazla olayı gözlemek için aracı seçin. İçerikler psikolojik okuryazarlık içindir; tanı veya kişisel tedavi yönergesi değildir.</p></section>
<section id="psikolojik-sorunlar"><h2>Psikolojik sorunlar</h2><p>Ana sayfada yer alan ve her bir zorlanmayı ayrı ayrı açıklayan yazıları burada topluca inceleyebilirsiniz.</p><div class="library-grid">
<article class="library-card"><span class="library-label">Sosyal değerlendirilme</span><h3><a href="/sosyal-kaygi">Sosyal Kaygı</a></h3><p>Başkalarının değerlendirmesiyle ilgili yoğun kaygıyı, kaçınmayı ve döngüyü genel hatlarıyla açıklar.</p></article>
<article class="library-card"><span class="library-label">Duygu ve geri çekilme</span><h3><a href="/depresyon">Duygu Çökkünlüğü</a></h3><p>Çökkün duygu durumu, ilgi kaybı, enerji düşüklüğü ve geri çekilme döngüsünü ele alır.</p></article>
<article class="library-card"><span class="library-label">Travma sonrası tepkiler</span><h3><a href="/travma">Travma Sonrası Tepkiler</a></h3><p>İstenmeyen anılar, tetiklenme, bedensel alarm ve kaçınma gibi travma sonrası tepkileri açıklar.</p></article>
<article class="library-card"><span class="library-label">Obsesyon ve kompulsiyon</span><h3><a href="/okb">Zorlayıcı Düşünceler (OKB)</a></h3><p>Zihne zorla gelen düşünceler ile rahatlama amacıyla tekrarlanan davranışların oluşturduğu döngüyü inceler.</p></article>
<article class="library-card"><span class="library-label">Özgül korku</span><h3><a href="/yukseklik-korkusu">Yükseklik Kaygısı</a></h3><p>Yüksekte hissedilen bedensel alarmı, düşme endişesini ve kaçınmanın etkisini açıklar.</p></article>
<article class="library-card"><span class="library-label">Bedensel alarm</span><h3><a href="/panik-atak">Panik Atak</a></h3><p>Yoğun bedensel duyumların felaket olarak yorumlanmasıyla büyüyebilen panik döngüsünü ele alır.</p></article>
<article class="library-card"><span class="library-label">Sürekli endişe</span><h3><a href="/genel-kaygi">Genel Kaygı</a></h3><p>Olumsuz senaryolar, belirsizlik ve bedensel gerginlikle sürebilen genel kaygı örüntüsünü açıklar.</p></article>
<article class="library-card"><span class="library-label">Belirli nesne veya durum</span><h3><a href="/ozgul-fobi">Özgül Fobiler</a></h3><p>Belirli bir nesne ya da durumda yükselen yoğun korkuyu ve kaçınma döngüsünü inceler.</p></article></div></section>
<section id="ogrenme-yollari"><h2>Öğrenme yolları</h2><div class="library-grid">
<article class="library-card"><span class="library-label">Tam sıralı yol</span><h3><a href="/ogrenme-yollari/kaygi">Kaygıyı anlama ve çalışma</a></h3><p>Genel çerçeve → kaygı döngüsü → kaçınma haritası → işlevsel takip → esneklik → destek.</p></article>
<article class="library-card"><span class="library-label">Panik yolu</span><h3><a href="/panik-atak">Panik ve bedensel alarm</a></h3><p>Panik çerçevesi → <a href="/panik-atak-belirtileri">belirtiler</a> → <a href="/panik-atak-aninda-ne-yapmali">atak anı</a> → <a href="/araclar/panik-atak-ani-plani">kişisel plan</a>.</p></article>
<article class="library-card"><span class="library-label">Sosyal kaygı yolu</span><h3><a href="/sosyal-kaygi">Sosyal değerlendirilme kaygısı</a></h3><p>Genel çerçeve → <a href="/sosyal-kaygi-belirtileri">belirtiler</a> → <a href="/sosyal-kaygi-neden-olur">sürdüren süreçler</a> → <a href="/uygulamalar/kacinma-haritasi">kaçınma haritası</a>.</p></article>
<article class="library-card"><span class="library-label">OKB yolu</span><h3><a href="/okb">Obsesyon ve kompulsiyon döngüsü</a></h3><p>Genel çerçeve → <a href="/okb-belirtileri">belirtiler</a> → <a href="/kompulsiyon-nedir">kompulsiyon</a> → <a href="/maruz-birakma-terapisi">exposure mantığı</a>.</p></article>
<article class="library-card"><span class="library-label">Esneklik yolu</span><h3><a href="/psikolojik-esneklik">Psikolojik esneklik</a></h3><p>Esneklik → <a href="/yasantisal-kacinma">yaşantısal kaçınma</a> → <a href="/bilissel-ayrisma">ayrışma</a> → <a href="/degerler-calismasi">değerler</a> → <a href="/kabul-ne-demek">kabul</a>.</p></article></div></section>
<section id="rehberler"><h2>Açıklayıcı rehberler</h2><div class="library-grid"><article class="library-card"><span class="library-label">Mekanizma</span><h3><a href="/kaygi-dongusu">Kaygı Döngüsü</a></h3><p>Kaygının kaçınma ve kısa vadeli rahatlamayla nasıl sürebildiğini altı halka üzerinden açıklar.</p></article><article class="library-card"><span class="library-label">Davranış ve işlev</span><h3><a href="/davranis-analizi-nedir">Davranış analizi</a></h3><p>Davranışın biçiminden çok bağlamını ve sonuçlarını anlamak için temel çerçeve.</p></article><article class="library-card"><span class="library-label">Duygu ve davranış</span><h3><a href="/yasantisal-kacinma">Yaşantısal kaçınma</a></h3><p>Zor iç deneyimleri kontrol etme çabasının yaşamı ne zaman daralttığını inceler.</p></article><article class="library-card"><span class="library-label">Değişim</span><h3><a href="/psikolojik-esneklik">Psikolojik esneklik</a></h3><p>Zor iç deneyimler varken önemli yöne hareket edebilme kapasitesini açıklar.</p></article></div></section>
<section id="uygulamalar"><h2>Güvenli psikoeğitim uygulamaları</h2><div class="library-grid"><article class="library-card"><span class="library-label">10–15 dakika</span><h3><a href="/uygulamalar/kacinma-haritasi">Kaçınma Haritası</a></h3><p>Tek bir olayda davranışın kısa vadeli işlevini, uzun vadeli maliyetini ve küçük esneme adımını görünür kılar.</p></article><article class="library-card"><span class="library-label">Önce okuma</span><h3><a href="/kaygi-dongusu">Uygulamadan önce mekanizmayı anlayın</a></h3><p>Bir davranışı aceleyle “kaçınma” diye etiketlemeden önce işlevsel çerçeveyi okuyun.</p></article></div></section>
<section id="araclar"><h2>Tekrar kullanılabilir araçlar</h2><div class="library-grid"><article class="library-card"><span class="library-label">CSV / yazdırma</span><h3><a href="/araclar/islevsel-takip">İşlevsel Takip Formu</a></h3><p>Birden fazla olayda öncesi, davranış, kısa ve uzun vadeli sonuçları izleyin.</p></article><article class="library-card"><span class="library-label">Tek olay</span><h3><a href="/araclar/kaygi-dongusu-haritasi">Kaygı Döngüsü Haritası</a></h3><p>Tetikleyici, düşünce, beden ve davranış bağlantısını ayrıntılı metne dönüştürün.</p></article><article class="library-card"><span class="library-label">Panik</span><h3><a href="/araclar/panik-atak-ani-plani">Panik Atak Anı Planı</a></h3><p>Atak anında hatırlanacak kısa ve kişisel bir plan oluşturun.</p></article><article class="library-card"><span class="library-label">Tüm araçlar</span><h3><a href="/araclar">Araç kütüphanesi</a></h3><p>Tarayıcıda çalışan psikolojik harita ve planları birlikte görün.</p></article></div></section>
<section id="yaklasimlar"><h2>Yaklaşımlar ve süreçler</h2><div class="guide-index"><article class="library-card"><h3>ACT ve psikolojik esneklik</h3><p><a href="/act-nedir">ACT nedir?</a> · <a href="/psikolojik-esneklik">Esneklik</a> · <a href="/degerler-calismasi">Değerler</a> · <a href="/bilissel-ayrisma">Ayrışma</a></p></article><article class="library-card"><h3>PBT ve davranış analizi</h3><p><a href="/pbt-nedir">PBT nedir?</a> · <a href="/psikolojik-surec-haritasi">Süreç haritası</a> · <a href="/davranis-analizi-nedir">Davranış analizi</a></p></article><article class="library-card"><h3>BDT ve davranışsal yöntemler</h3><p><a href="/bdt-nedir">BDT nedir?</a> · <a href="/maruz-birakma-terapisi">Exposure</a> · <a href="/davranissal-aktivasyon">Davranışsal aktivasyon</a></p></article><article class="library-card"><h3>Görüşme ve destek</h3><p><a href="/baslangic">Başlangıç</a> · <a href="/surec">Süreç</a> · <a href="/online-psikolog">Online görüşme</a> · <a href="/hakkimda">Hakkımda</a></p></article></div></section>
<section class="guide-callout warning"><strong>Güvenlik notu:</strong><p>Bu kütüphane acil yardım veya tanı hizmeti değildir. Kendine zarar verme riski, güvenliği sürdürememe veya acil tıbbi durum varsa 112'yi arayın ya da en yakın acil servise başvurun.</p></section>'''

page("/site-haritasi", "Psikoloji Rehberleri, Uygulamalar ve Araçlar | Ata Pamukçu", "Kaygı, panik, sosyal kaygı, OKB ve psikolojik esneklik için açıklayıcı rehberler, güvenli uygulamalar, çalışma araçları ve sıralı öğrenme yolları.", "Evergreen psikoloji kütüphanesi", "Psikoloji Rehberleri ve Öğrenme Yolları", "Bir konuyu anlamak, uygulamak ve takip etmek için rehberleri, güvenli psikoeğitim uygulamalarını ve tarayıcıda çalışan araçları amaçlarına göre seçin.", library_body, schema_type="CollectionPage", og_type="website")

print("\n".join(str(p.relative_to(ROOT)) for p in [ROOT/'kaygi-dongusu.html', ROOT/'uygulamalar/kacinma-haritasi.html', ROOT/'araclar/islevsel-takip.html', ROOT/'ogrenme-yollari/kaygi.html', ROOT/'site-haritasi.html']))
